name: Run code format checkers
on: [push]

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.1.13']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup python environment
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Upgrade pip
        run: |
          pip install --upgrade pip


      - name: Run formatters
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
